controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

api_login:
    path: /api/login
    controller: Lexik\Bundle\JWTAuthenticationBundle\Controller\AuthenticationController::login
    methods: [POST]