nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173','http://localhost:5174', 'https://ton-react-production.com']  # ← Mets ici l'URL exacte de ton React en ligne
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/theo/site-ecommerce/backend/public/index.php/':
            allow_origin: ['http://localhost:5173','http://localhost:5174', 'https://ton-react-production.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
