nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173', 'http://localhost:5174', 'https://ton-react-production.com']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/': # Utiliser un chemin racine pour capturer toutes les routes
            allow_origin: ['http://localhost:5173', 'http://localhost:5174', 'https://ton-react-production.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']