nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/': # Utiliser un chemin racine pour capturer toutes les routes
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']