nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173','http://localhost:5174/']
        allow_headers: ['Content-Type', 'Authorization', 'X-API-TOKEN']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/':
            allow_origin: ['http://localhost:5173','http://localhost:5174/']
            allow_headers: ['Content-Type', 'Authorization', 'X-API-TOKEN']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
