security:
    # Gestion des encodages des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  

    firewalls:
        # Firewall API
        api:
            pattern: ^/api/       
            stateless: true      
            json_login:           
                check_path: /api/login
                username_path: email
                password_path: password

        # Firewall principal (site web classique)
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800       
                path: /
                always_remember_me: true

    access_control:
    # Autoriser l'accès à la route de login pour les utilisateurs anonymes et authentifiés
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # Autoriser les autres routes API uniquement pour les utilisateurs authentifiés
        - { path: ^/api, roles: ROLE_USER }

    # Les routes d'administration nécessitent ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
